dist: jammy
language: c
cache: ccache
compiler: clang
git:
  submodules: false

jobs:
  include:

    - arch: ppc64le
      addons:
        apt_packages: clang qemu-system-ppc
      env:
      - CONFIG="--arch=ppc64 --endian=little --cc=clang --cflags=-no-integrated-as"
      - TESTS="emulator rtas-get-time-of-day rtas-get-time-of-day-base
          rtas-set-time-of-day selftest-setup spapr_hcall"

    - arch: s390x
      dist: focal
      addons:
        apt_packages: clang-11 qemu-system-s390x
      env:
      - CONFIG="--arch=s390x --cc=clang-11 --cflags=-no-integrated-as"
      - TESTS=""

before_script:
  - mkdir -p build && cd build
  - $TRAVIS_BUILD_DIR/configure $CONFIG
script:
  - make -j3
  - if [ -n "$TESTS" ]; then
      ACCEL="${ACCEL:-tcg}" ./run_tests.sh -v $TESTS | tee results.txt &&
      grep -q PASS results.txt && ! grep -q FAIL results.txt ;
    fi
