dist: focal
language: c
cache: ccache
compiler: clang
git:
  submodules: false

jobs:
  include:

    - arch: arm64
      addons:
        apt_packages: qemu-system-aarch64
      env:
      - CONFIG="--arch=arm64 --cc=clang"
      - TESTS="cache gicv2-active gicv2-ipi gicv2-mmio gicv3-active gicv3-ipi
          pci-test pmu-cycle-counter pmu-event-counter-config pmu-sw-incr
          selftest-setup selftest-smp selftest-vectors-kernel
          selftest-vectors-user timer"

before_script:
  - mkdir -p build && cd build
  - $TRAVIS_BUILD_DIR/configure $CONFIG
script:
  - make -j3
  - qemu-system-aarch64 -M virt -kernel arm/gic.flat -smp 8 -machine gic-version=2 -append 'mmio'
  - if [ -n "$TESTS" ]; then
      ACCEL="${ACCEL:-tcg}" ./run_tests.sh -v $TESTS | tee results.txt &&
      grep -q PASS results.txt && ! grep -q FAIL results.txt ;
    fi
  - ls logs
  - cat logs/gicv2-mmio.log
